export const routes = {
  auth: {
    login: 'login',
    register: 'register',
    logout: 'logout',
    forgotPassword: 'password.request',
    confirmPassword: 'password.confirm',
    permissions: {
      index: 'permissions.index',
      check: 'permissions.check',
    },
  },
  dashboard: {
    index: 'dashboard',
    overview: {
      index: 'dashboard',
    },
    brands: {
      index: 'brands.index',
      create: 'brands.create',
      store: 'brands.store',
      edit: 'brands.edit',
      update: 'brands.update',
      destroy: 'brands.destroy',
      deleteMany: 'brands.delete-many',
      restoreMany: 'brands.restore-many',
    },
    categories: {
      index: 'categories.index',
      create: 'categories.create',
      store: 'categories.store',
      edit: 'categories.edit',
      update: 'categories.update',
      destroy: 'categories.destroy',
      deleteMany: 'categories.delete-many',
      restoreMany: 'categories.restore-many',
    },
    products: {
      index: 'products.index',
      create: 'products.create',
      store: 'products.store',
      edit: 'products.edit',
      update: 'products.update',
      destroy: 'products.destroy',
      deleteMany: 'products.delete-many',
      restoreMany: 'products.restore-many',
    },
    variants: {
      index: 'variants.index',
      create: 'variants.create',
      store: 'variants.store',
      edit: 'variants.edit',
      update: 'variants.update',
      destroy: 'variants.destroy',
      deleteMany: 'variants.delete-many',
      restoreMany: 'variants.restore-many',
    },
    images: {
      destroy: 'images.destroy',
    },
    settings: {
      index: 'settings',
      users: {
        index: 'users.index',
        create: 'users.create',
        store: 'users.store',
        edit: 'users.edit',
        update: 'users.update',
        destroy: 'users.destroy',
        deleteMany: 'users.delete-many',
        restoreMany: 'users.restore-many',
        resendVerifyEmail: 'users.resend-verify-email',
      },
      roles: {
        index: 'roles.index',
        create: 'roles.create',
        store: 'roles.store',
        edit: 'roles.edit',
        update: 'roles.update',
        destroy: 'roles.destroy',
        deleteMany: 'roles.delete-many',
      },
    },
  },
  client: {
    index: 'home',
    about: 'about',
    contact: 'contact',
    faqs: 'faqs',
  },
};
